// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGlm9_6KPhwUGvvXDbcTIiE8WPrYYKwA',
    appId: '1:486759824037:web:3f58b6cfbafc6c37e4eb4c',
    messagingSenderId: '486759824037',
    projectId: 'al-alamia-af2d9',
    authDomain: 'al-alamia-af2d9.firebaseapp.com',
    storageBucket: 'al-alamia-af2d9.firebasestorage.app',
    measurementId: 'G-YQDLC2RVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9on0h4s1hOKd60gt0gRqJTkr_vhFu8Q',
    appId: '1:486759824037:android:b8c2d023d6995247e4eb4c',
    messagingSenderId: '486759824037',
    projectId: 'al-alamia-af2d9',
    storageBucket: 'al-alamia-af2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMgFQSmHTb4m_DUpFkQsRZGLcM8dLVXI',
    appId: '1:486759824037:ios:84f4270fc7d11c1ce4eb4c',
    messagingSenderId: '486759824037',
    projectId: 'al-alamia-af2d9',
    storageBucket: 'al-alamia-af2d9.firebasestorage.app',
    iosBundleId: 'com.example.alalamia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMgFQSmHTb4m_DUpFkQsRZGLcM8dLVXI',
    appId: '1:486759824037:ios:84f4270fc7d11c1ce4eb4c',
    messagingSenderId: '486759824037',
    projectId: 'al-alamia-af2d9',
    storageBucket: 'al-alamia-af2d9.firebasestorage.app',
    iosBundleId: 'com.example.alalamia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaGlm9_6KPhwUGvvXDbcTIiE8WPrYYKwA',
    appId: '1:486759824037:web:0f0dfbfc1c9f12fce4eb4c',
    messagingSenderId: '486759824037',
    projectId: 'al-alamia-af2d9',
    authDomain: 'al-alamia-af2d9.firebaseapp.com',
    storageBucket: 'al-alamia-af2d9.firebasestorage.app',
    measurementId: 'G-QE84PJP232',
  );
}
